### ISSUE TITLE
Custom TitleBar background for Mac

### ISSUE THREAD

**Issue by turshija** [gabrielbull/react-desktop#105]
I'm trying to make dark app, but can't seem to change TitleBar color to get effect like this:
![image](https://user-images.githubusercontent.com/933433/34263212-01089f54-e66f-11e7-8b17-582a16e35ca7.png)

I've tried using "transparent" prop, but with no success.

**Comment by gabrielbull** [comment]
Please submit a PR and we will be glad to accept it. Thanks.

**Comment by davej** [comment]
@turshija: You can achieve this by setting `transparent` and `inset` properties:

```js
import MacTitleBar from 'react-desktop/src/TitleBar/macOs';

<TitleBar
  controls={true}
  transparent={true}
  inset={true}
/>
```

Closing this issue
