### ISSUE TITLE
:active class lost for Button component

### ISSUE THREAD

**Issue by alacroix** [gabrielbull/react-desktop#115]
Hey @gabrielbull,

I was trying to implement `styled-components` on the Button component but I wasn't able to get the active effect on the playground.

I suspect the update of Radium to version ^0.21.2 on [this commit](b6cc2a6) to be the culprit.

If I reset to the old version, it works again. I didn't test on other components but I suspect every `:active` and other Radium style to be broken right now.

Maybe downgrade Radium version for now or check the breaking changes for the updated version while we switch to `styled-components`

**Comment by gabrielbull** [comment]
Ok, I reverted radium back to "=0.19.6" on the master branch. Can you publish a branch with your changes so I can play around as well? Maybe call it styled-components. Thanks!

**Comment by alacroix** [comment]
@gabrielbull, sure! I'm on `jest` right now but when I'll resume my work on `styled-components`, i'll push what i've done 👍

**Comment by alacroix** [comment]
Fixed with 15c92fba7765a0a8077d6990d43a985da4ae5738
