### ISSUE TITLE
customize font-size for Windows/Text

### ISSUE THREAD

**Issue by sosunnyproject** [gabrielbull/react-desktop#116]
Hello, 
I cannot find a way to customize font-size of windows Text element.

I imported like below,
`import { Text } from 'react-desktop/windows';`
and wrote my code like this
```
<div>
<Text horizontalAlignment= 'center' color= 'white' font-size='20px'>Photo</Text>
//few other elements
</div>
```

I tried fontSize, font-size, size ... but couldn't find a way to edit it. 
Would you please let me know what's the variable name I can customize font size?

Thanks!

**Comment by 98oktay** [comment]
Hi,
try this:

`<Text horizontalAlignment= 'center' color= 'white' style={{fontSize:'20px'}}>Photo</Text>`

**Comment by sosunnyproject** [comment]
Yes this works! Thank you!
