### ISSUE TITLE
Did react-desktop supported canvas ?

### ISSUE THREAD

**Issue by zjuwjf** [gabrielbull/react-desktop#122]
Did react-desktop supported canvas ?

**Comment by gabrielbull** [comment]
Can you elaborate, I do not understand the question.

**Comment by jeffvandyke** [comment]
(mb close to clean up issues board?)

This library uses React components that style HTML buttons and inputs (etc...), and you should be able to use canvas along with react-desktop - it will function like a normal canvas.

**Comment by davej** [comment]
@jeffvandyke Thanks
