### ISSUE TITLE
macOS Mojave and dark mode

### ISSUE THREAD

**Issue by holgersindbaek** [gabrielbull/react-desktop#137]
It seems like this is the only Electron Native UI library still being maintained. Is there any plans on updating the project to make the UI look completely like macOS Mojave? Is there any plan to support Mojave's dark theme feature?

**Comment by davej** [comment]
No plans AFAIK.
PRs are accepted though if it's something that you wanted to work on.

**Comment by holgersindbaek** [comment]
Ok. I might do something. Thanks for the quick answer.

**Comment by hadnet** [comment]
> Ok. I might do something. Thanks for the quick answer.

Any update on this?
