### ISSUE TITLE
Toggling windows doesnt show anything!

### ISSUE THREAD

**Issue by ShashankaNataraj** [gabrielbull/react-desktop#14]

**Comment by Salakar** [comment]
Can you explain your issue please? If you mean the toggle to show Windows components then you should still see a window, there's just no more completed Windows comps yet, though I did push the start of a couple new ones today!

**Comment by ShashankaNataraj** [comment]
Sorry if I wasn't clear, this is what I mean:

![bug](https://cloud.githubusercontent.com/assets/650317/10559388/76a92eb6-750d-11e5-9625-b4cf9450b9fa.png)

**Comment by Salakar** [comment]
Ah ye, as above then :) still working on the windows components so there isn't any to show yet, there's a couple that are WIP (label, button, textfield etc), keep an eye out, they'll be there soon.
