### ISSUE TITLE
There's something wrong with the title bar.

### ISSUE THREAD

**Issue by langyo** [gabrielbull/react-desktop#141]
#65 
I have used it for my electron application, but there is something wrong.

## 1. Window border doesn't render properly in electron.
If I set the width and height of the props window to match the width and height of the electron window, the window will not display completely.
![25c5cc.png](https://miao.su/images/2019/03/09/25c5cc.png)
Here's the creation code for the electron window:
```
function createMainWnd() {
    mainWnd = new BrowserWindow({
        width:800,
        height:600,
        useContentSize: true,
        show: false,
        frame: false,
        transparent: true
    });

    mainWnd.loadURL(`file://${__dirname}/public/index.html`);

    mainWnd.on('ready-to-show', ()=>{
        Menu.setApplicationMenu(null);
        mainWnd.show();
        // mainWnd.webContents.openDevTools({ detach:true });
    });

  mainWnd.on('closed', () => {
    mainWnd = null;
    process.exit();
  });
}
```
And here's the react desktop's component JSX:
```
<Window
  color={this.props.color}
  theme={this.props.theme}
  chrome
  height="600px"
  width="800px"
>
```
If I set the window size to 808 * 608, and set the window transparent, it will work properly.

## 2. The upper-right control bar does not display normally.
![10ade5.gif](https://miao.su/images/2019/03/09/10ade5.gif)
Some control buttons cover the window border.

This may only happen in electron applications, but it does have an impact on the visual effect.

@gabrielbull

**Comment by langyo** [comment]
If you need, I can help maintain the project, and I'll fix it myself.
@gabrielbull

**Comment by davej** [comment]
Hi @langyo, I'm happy to review and merge a PR for you?

**Comment by langyo** [comment]
> Hi @langyo, I'm happy to review and merge a PR for you?

Yep, thanks!
I'll remind you when I send PR.

**Comment by davej** [comment]
@langyo A reminder on this if you have the chance. :-)

**Comment by langyo** [comment]
> @langyo A reminder on this if you have the chance. :-)

I've been too busy in the last three months. Maybe I can make time to repair it in July.

:P

**Comment by langyo** [comment]
#143
