### ISSUE TITLE
Demo / Docs Website Changelog not Updating!

### ISSUE THREAD

**Issue by Dilks44** [gabrielbull/react-desktop#165]
It seems as if this website content is no longer tracking the changelog file in this repo.
Website - http://reactdesktop.js.org/docs/CHANGELOG
file - https://github.com/gabrielbull/react-desktop/blob/master/CHANGELOG.md

When I click "Edit Page" on the website I am linked to "https://github.com/gabrielbull/react-desktop/edit/master/docs/CHANGELOG.md" which throws a 404.

**Comment by langyo** [comment]
The website itself has not been updated much since 2018...

Currently this project is no longer actively maintained, so there is no one to take care of the website.

If you have time, you can submit a merge request to update the changelog. :P

**Comment by Dilks44** [comment]
Ah you are right, forgot to check the date. Also just noticed that this repo doesn't contain the website content, so I may not be able to fix that after all. Unless the author decides to open source that as well.

**Comment by gabrielbull** [comment]
@Dilks44 It's on the `gh-pages` branch.
