### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by steelbrain** [gabrielbull/react-desktop#19]
The docs and description only mentions windows 10 and OSX, why doesn't it work on linux? Both the electron and node-webkit work on it btw.

**Comment by chentsulin** [comment]
I think this works great on linux now, but just don't have linux style components.

**Comment by Salakar** [comment]
Aye it does work on linux, the description means only win 10 and OSX styled components are available, can still use the OSX or windows components on Linux.

**Comment by gabrielbull** [comment]
@steelbrain Hi, do you mean it lacks a Linux UI? That is something that could be added in the future. Right now the focus is on OS X and Windows, but the library will work fine on Linux, you'll just end up with a UI that looks like OS X or Windows. I'm closing his now as it is not really an issue! Thanks!

**Comment by steelbrain** [comment]
@gabrielbull If you're gonna add the linux UI in the future, then I think it's better to keep this open till then

**Comment by gabrielbull** [comment]
Maybe, but this issue seems to indicate that the library does not work on Linux, which is false. Maybe you could create an issue to discuss the creation of a Linux UI.

**Comment by steelbrain** [comment]
I would really appreciate if someone else would do it.

**Comment by gutenye** [comment]
Yes, change the name to 'Native Linux UI style support' is better, why everybody exclude Linux at the first place? Native Linux UI is as important as Mac OS X and Windows!

**Comment by mikew** [comment]
What is "Native Linux UI style" though? Qt? GTK? KDE? Wx?

**Comment by Salakar** [comment]
@mikew +1 - there's so many variations.

**Comment by jamrizzi** [comment]
I've been wanting to build a gtk react bridge for quite some time. Wondering if you'd be interested in me making it part of this project?

**Comment by gabrielbull** [comment]
@jamrizzi Please email me at me@gabrielbull.com to discuss collaboration. Thanks!
