### ISSUE TITLE
Documentation : For some of the links there is no text, only header and some redirect to '404'

### ISSUE THREAD

**Issue by dineshb-qa** [gabrielbull/react-desktop#27]
* Go to the URL = http://gabrielbull.github.io/react-desktop/docs/

* Observe that for following URL's there is only header and no other text. On page reload the header text also disappear : 
 * http://gabrielbull.github.io/react-desktop/docs/Installation 
 * http://gabrielbull.github.io/react-desktop/docs/advanced-usage/Electron-js
 * http://gabrielbull.github.io/react-desktop/docs/advanced-usage/node-webkit

* Observe that for following URL's '404 error' : 
 * http://gabrielbull.github.io/CONTRIBUTING
 * http://gabrielbull.github.io/Testing
 * http://gabrielbull.github.io/FAQ
 * http://gabrielbull.github.io/CHANGELOG

**Comment by gabrielbull** [comment]
Fixed. Thanks for reporting.
