### ISSUE TITLE
No way to hide a `Form.Row` element

### ISSUE THREAD

**Issue by zalmoxisus** [gabrielbull/react-desktop#48]
There are [states](https://github.com/gabrielbull/react-desktop/blob/master/src/form/form.common/row/row.js#L47) responsible for that, but they're never changed. We cannot pass `display` style as well as [it is overwritten](https://github.com/gabrielbull/react-desktop/blob/master/src/form/form.common/row/row.js#L80).

I'll make a pull request to solve that when the refactoring is over, as for now [the import paths of the modules doesn't match the directory structure](https://travis-ci.org/gabrielbull/react-desktop/jobs/101210301).

**Comment by gabrielbull** [comment]
Forms have been removed for now.
