### ISSUE TITLE
Documentation Status

### ISSUE THREAD

**Issue by stefanKuijers** [gabrielbull/react-desktop#49]
What is the current status of the documentation? I would really love to use this project in a electron app but I am new to electron and react and would really appreciate at least some kind of installation guide and a kitchen sink. 

I assume that this is available somewhere but I can't find it now. Is this still coming or can someone point me to it?

**Comment by gabrielbull** [comment]
Hi @stefanKuijers ,

This is still a work in progress and the most up to date documentation is available here: https://github.com/gabrielbull/react-desktop/tree/master/docs

The current state is that the Windows version is almost finished and the API should not change too much when using it. The Mac version is being refactored and once it is finished, I should be able to release a first stable version. The current E.T.A. for the stable release is June. 

There is no documentation for installation currently available but if you have an electron app running, it should be as simple as installation this package using the command `npm install --save react-desktop` and then you should be able to use the examples in the doc.

**Comment by stefanKuijers** [comment]
Thank you so much. I will see or I can get it working.
