### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by Semigradsky** [gabrielbull/react-desktop#50]
After click "Forms" in Windows view:
- > Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `t`.

- > Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `t`.

- > Uncaught Invariant Violation: findComponentRoot(..., .1.$win.0.$/=11.$//=10/=1$/=010.$////=11///=1$///=011//=1$///=011//=01$//=0011/=11=2$///=011//=01$//=0011/=01$//=0011/=001$/=00011.0.$/=11.0.$=1$/=01$=001$=0001$=00001$=000001$=00000013.$=1$=01$=001$=0001$=000013.$/=10.$/=10): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID ``.

**Comment by gabrielbull** [comment]
Thanks for reporting. It is now fixed!
