### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by imaaronzhang** [gabrielbull/react-desktop#55]
Hi

Thank you! This is a great work. I wanted to have a try, but it happens  error when npm install. 
 
npm ERR! peerinvalid The package react@15.1.0 does not satisfy its siblings' peerDependencies requirements!
.....
npm ERR! peerinvalid Peer material-ui@0.15.0 wants react@^15.0.0
npm ERR! peerinvalid Peer react-tap-event-plugin@1.0.0 wants react@^15.0.0-0
npm ERR! peerinvalid Peer react-desktop@0.2.0 wants react@~15.0

**Comment by gabrielbull** [comment]
Hi, thanks for letting me know! I've just publish a new version that will accept react 15.1 as a peer dependency.
