### ISSUE TITLE
Integrate with electron-react-boilerplate style problem

### ISSUE THREAD

**Issue by xgenvn** [gabrielbull/react-desktop#64]
I'm trying to integrate react desktop components into a boilerplate by [electron-react-boilerplate](https://github.com/chentsulin/electron-react-boilerplate).
Already set the frame option to false, tweak the margin to zero, I got the overflow scrollbar:
![image](https://cloud.githubusercontent.com/assets/559443/17722779/6bf1ae40-6467-11e6-92fa-fe06c8faba22.png)

If I set the body style to overflow: hidden, the border of main window won't be able to display (due to overflow). In the snip below, right border is not showing.

![image](https://cloud.githubusercontent.com/assets/559443/17722804/a2d1a6e0-6467-11e6-83b2-75b651a30b13.png)

Since the stylesheet of the boilerplate is pretty simple, I'm not really sure whether I miss any option. Any suggestion will be appreciated.

**Comment by gabrielbull** [comment]
Can you zip and share the boilerplate you made?

**Comment by xgenvn** [comment]
This is just a basic boilerplate with some tweaks I mentioned above. Actually, the original repo suggests react-desktop for native looking, so I try to integrate into the sample project and there goes some UI issues.
[electron-react-boilerplate.zip](https://github.com/gabrielbull/react-desktop/files/421886/electron-react-boilerplate.zip)

**Comment by gabrielbull** [comment]
Hi. I just released a new version containing a fix for your issue. Please update your react-desktop dependency to `0.2.12`. Thanks for reporting the issue, let me know if there are any more issues.

**Comment by xgenvn** [comment]
Awesome! I have checked again and updated to last version, the issue is solved perfectly. Thank you.
