### ISSUE TITLE
How to use refs to access TextInput value

### ISSUE THREAD

**Issue by luayalshawi** [gabrielbull/react-desktop#67]
Hi,

I am having a problem accessing the TextInput value. I have tried to use onChange then from there I set the state but that caused a weird behavior. 

Is there a way to use ref with TextInput and be able to use it to access the input value?

```
      <TextInput
        ref="input"
        theme={this.props.theme}
        color={this.props.color}
        background
        label="My Input"
        placeholder="My Input"
        onChange={this.handleChange}
      />
```

by doing console.log(this.refs.input.value), I get undefined.

I am trying to use the input value based on click event that is coming from a button.

Any suggestions?

Thanks,

**Comment by luayalshawi** [comment]
```
        <TextInput
          theme={this.props.theme}
          color={this.props.color}
          background
          label="My Input"
          placeholder="My Input"
          onChange={this.handle.bind(this)}
          id="thisInput"
        />

```
Currently I am getting the value by having id as a prop then I can use the following line to get the input value:
`document.getElementById('thisInput').getElementsByTagName('input')[0].value)
`

**Comment by gabrielbull** [comment]
Hi @luayalshawi. Thanks for reporting the issue. I will take a look when I have some more time. In the meantime, check out the [React documentation for inputs](https://facebook.github.io/react/docs/forms.html), it could give you some clues on an alternative to refs. Like this example:

```jsx
  getInitialState: function() {
    return {value: 'Hello!'};
  },
  handleChange: function(event) {
    this.setState({value: event.target.value});
  },
  render: function() {
    return (
      <input
        type="text"
        value={this.state.value}
        onChange={this.handleChange}
      />
    );
  }
```

**Comment by gabrielbull** [comment]
You can now use ref to get value from input. Thanks for submitting the issue 🎉!

**Comment by luayalshawi** [comment]
Thanks
