### ISSUE TITLE
Windows TextInput onChange triggers dupe action

### ISSUE THREAD

**Issue by steamIngenius** [gabrielbull/react-desktop#68]
Every time a user types a character in the TextInput the onChange callback fires twice and the input loses focus. If I use the TextInput from 'react-desktop/macOs' instead everything works fine. My code:

        <TextInput
          value={serverField}
          width="200"
          label="Server"
          theme="dark"
          onChange={e => setServerField(e.target.value)} />

**Comment by gabrielbull** [comment]
Hey @steamIngenius, thanks for reporting the issue. I've published a new version with a fix for the duplicate onChange events. You need to update react-desktop to `0.2.14`. Cheers!

**Comment by steamIngenius** [comment]
Thanks for your quick attention to this!

**Comment by jaloo555** [comment]
Issue still seems to occur with react-desktop/windows?
my code
<TextInput
                        theme='light'
                        color='#cc7f29'
                        label="label"
                        type="text"
                        value={this.state.id}
                        onChange={this.handleIDChange}
                      />
