### ISSUE TITLE
Window background prop broken for Windows components

### ISSUE THREAD

**Issue by dotcarls** [gabrielbull/react-desktop#70]
Looks like the code for the background color has been commented out of [this file](https://github.com/gabrielbull/react-desktop/blob/master/src/window/windows/window.js):

``` js
    //if (this.state.background) {
      //componentStyle = { ...componentStyle, backgroundColor: this.state.background };
    //}
```

Docs should be updated or this should be uncommented :)

**Comment by gabrielbull** [comment]
@dotcarls Thanks for reporting. I'll investigate this tomorrow.

**Comment by gabrielbull** [comment]
@dotcarls sorry for the delay, the issue has now been resolved. Thanks for reporting! 🎉
