### ISSUE TITLE
Conditional Module Loading

### ISSUE THREAD

**Issue by stdavis** [gabrielbull/react-desktop#71]
I've noticed that the components in this project seem to mirror each other between macOS and windows. I assume that this is to enable developers to write the same code for both platforms? What's the suggested way of conditionally loading the correct component based upon the current platform? I don't think that something like this is supported:

``` js
if (process.platform === 'win32') {
    import { Window, TitleBar, Text } from 'react-desktop/windows'
} else {
    import { Window, TitleBar, Text } from 'react-desktop/macOs'
}
```

Imports have to be top level statements. 

I've also experimented with something like this:

``` js
const platform = (process.platform === 'win32') ? 'windows' : 'macOs';

import { Window, TitleBar, Text } from `react-desktop/${platform}`
```

This doesn't work because import statements don't support string templates (or variables for that matter).

Any other ideas? Do I need to switch to SystemJS or something?

**Comment by obedm503** [comment]
maybe because you forgot the `$` in the template string?

```js
const platform = (process.platform === 'win32') ? 'windows' : 'macOs';

import { Window, TitleBar, Text } from `react-desktop/${platform}`
```

not sure tho

**Comment by stdavis** [comment]
Good catch. I'm still getting used to template strings and have updated my code. However, it didn't make any difference. :(

**Comment by denen99** [comment]
@stdavis did you ever solve this ? Curious as well.

**Comment by stdavis** [comment]
Nope. Let me know if you find anything.

**Comment by gabrielbull** [comment]
You can now import components based on the current OS like so:

```jsx
import { Window, TitleBar, Text } from `react-desktop`;
```

**Comment by obedm503** [comment]
so does `'react-desktop'` decicide what to import or does it import both versions of the module for us to decide?

**Comment by gabrielbull** [comment]
It decides what to import. If you want to decide you can import using `react-desktop/macOs` or `react-desktop/windows`
