### ISSUE TITLE
library agnostic?

### ISSUE THREAD

**Issue by obedm503** [gabrielbull/react-desktop#73]
are there plans to make react-desktop library agnostic/independent?
 It would be great if there was a "web components version" that could be used without any framework or library. **A "native" implementation would open it to a much larger market.** I could be used with angular, ember, aurelia, polymer, and even vanilla js, all within Electron.

If not does anyone know of any non-framework-specific implementation of the mac and windows ui's? I've already looked into Photon, but that only provides mac ui.

**Comment by gabrielbull** [comment]
Hi @obedm503, while having it be library agnostic would be great, it would pivot too much from the goal of this one library and require too much change. Hope you find what you are looking for.
