### ISSUE TITLE
Unable to style label generated by TextInput

### ISSUE THREAD

**Issue by spmcbride1201** [gabrielbull/react-desktop#77]
Firstly, thanks so much for you work on this! I'm quite enthused to have such an easy experience building a Windows 10 themed Electron app.

My issue is that when my app is using the the dark theme, I can't style the labels associated with the <TextInput/> components. Based on your code examples, I was expecting the default behavior of these labels to be that they dynamically determine the color based on the theme, similar to what you suggest for the <Text/> components. My app is currently pulling UI settings from redux, and I'd like to be able to let the user toggle between light and dark themes (with the text reacting to the props appropriately). I'm likely going to strip out the labels and replace them with <Text/> components as a workaround, but if I'm missing something.

![image](https://cloud.githubusercontent.com/assets/8700322/21595606/b3cde88e-d0fd-11e6-840e-0e8104cc6bef.png)

**Comment by gabrielbull** [comment]
Hi, thanks for submitting the issue. The label should now change color based on theme for version 0.2.16. On top of that, you now have the ability to specify a color using the `labelColor` property and overwrite any label style using the `labelStyle` property. All info can be found in the docs. Cheers and happy new year!
