### ISSUE TITLE
[Windows] Minimize icon is not correct

### ISSUE THREAD

**Issue by levrik** [gabrielbull/react-desktop#79]
For comparsion:
![image](https://cloud.githubusercontent.com/assets/9491603/22024300/d31c66b6-dcc9-11e6-9a62-663836b5533f.png) React Desktop
![image](https://cloud.githubusercontent.com/assets/9491603/22024307/d97b1322-dcc9-11e6-9ac6-be9d22d6aec5.png) Native Windows 10

**Comment by gabrielbull** [comment]
Sorry for the late reply, but if someone is willing to submit a PR, I'd be happy to accept it.
